apiVersion: v1
kind: Secret
metadata:
  name: {{ template "overops-storage-server-s3.fullname" . }}
  labels:
    {{- include "overops-storage-server-s3.labels" . | nindent 4 }}
type: Opaque
stringData:
  settings.yaml: |-
    enableCors: true
    corsOrigins: /"*/"
    s3Fs:
      bucket: {{ .Values.overops.bucket }}
      pathPrefix: {{ .Values.overops.pathPrefix }}
      credentials:
        accessKey: {{ .Values.overops.accessKey }}
        secretKey: {{ .Values.overops.secretKey }}
    multifetch:
      concurrencyLevel: 100
      maxCacheSize: 67108864
      enableCacheLogger: false
      maxBatchSize: 4194304
    server:
      gzip:
        includedMethods: [POST, GET]    
      applicationConnectors:
        - type: http
          port: 8080
      adminConnectors:
        - type: http
          port: 8081
    logging:
      level: INFO
      loggers:
        com.takipi: DEBUG
      appenders:
        - type: console
