apiVersion: v2
name: overops-collector
description: A Helm chart for OverOps Collector v5
type: application
version: 5.0.6
appVersion: 5.0.0
icon: https://files.readme.io/7d44ac2-o-logo.ico
home: https://www.overops.com/
