{{- if .Values.externalDatabase.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "overops-server.fullname" . }}
  labels:
    {{- include "overops-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.externalDatabase.dbPassword  }}
  db-password:  {{ .Values.externalDatabase.dbPassword | b64enc | quote }}
  {{ end }}
{{- end }}