{{- if and .Values.database.external (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "overops-server.fullname" . }}
  labels:
    {{- include "overops-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mysql.mysqlPassword  }}
  db-password:  {{ .Values.mysql.mysqlPassword | b64enc | quote }}
  {{ end }}
{{- end }}