apiVersion: v2
name: overops
description: A Helm chart for OverOps Stack.
type: application
version: 0.10.1
appVersion: 4.63.1
icon: https://files.readme.io/7d44ac2-o-logo.ico
home: https://www.overops.com/


dependencies:
  - name: overops-server
    version: 0.10.1
    repository: https://overops.github.io/helm-charts/
    condition: overops-server.enabled

  - name: overops-collector
    version: 0.10.1
    repository: https://overops.github.io/helm-charts/
    condition: overops-collector.enabled

  - name: overops-event-generator
    version: 0.10.1
    repository: https://overops.github.io/helm-charts/
    condition: overops-event-generator.enabled

  - name: overops-java-bullshifier
    version: 0.2.2
    repository: https://overops.github.io/helm-charts/
    condition: overops-java-bullshifier.enabled

  - name: overops-storage-server
    version: 0.2.2
    repository: https://overops.github.io/helm-charts/
    condition: global.enableStorageServer

  - name: overops-storage-server-s3
    version: 0.2.2
    repository: https://overops.github.io/helm-charts/
    condition: global.enableStorageServerS3
