apiVersion: v1
kind: Service
metadata:
  name: {{ include "overops-collector.fullname" . }}
  {{- if eq .Values.service.loadBalancerType "nlb" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  {{- end }}
  labels:
    {{- include "overops-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6060
      protocol: TCP
      name: collector
  {{- if ne .Values.service.loadBalancerType "nlb" }}
  sessionAffinity: ClientIP
  {{- end }}
  selector:
    {{- include "overops-collector.selectorLabels" . | nindent 4 }}
