apiVersion: v1
kind: Service
metadata:
  name: {{ include "overops-collector.fullname" . }}
  labels:
    {{- include "overops-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6060
      protocol: TCP
      name: collector
  sessionAffinity: ClientIP      
  selector:
    {{- include "overops-collector.selectorLabels" . | nindent 4 }}
