apiVersion: v2
name: overops-java-bullshifier
description: A Helm chart for OverOps Java Bullshifier
type: application
version: 0.5.0
appVersion: 2.2.0-agent-4.58.0
icon: https://files.readme.io/7d44ac2-o-logo.ico
home: https://www.overops.com/
