# Default values for overops-storage-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overops Config settings for more info on Storage Server
# See https://doc.overops.com/docs/install-storage-server
overops:
  # Max Storage Percentage Used
  maxUsedStoragePercentage: 0.90
  # Number of days after which events last seen are to be deleted.
  retentionPeriodDays: 92
  # Enables Storage Server clean up task
  cleanupJobEnabled: true
  # Clean up task interval
  cleanupJobInterval: 6h

replicaCount: 1
image:
  repository: overops/storage-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
# Standard Pod Security Context to match the OverOps Image
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
securityContext: {}

service:
  type: ClusterIP
  port: 8080

# Standard Liveness Probe
livenessProbe:
  enabled: true
  periodSeconds: 10
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 1

# Standard Startup Probe
startupProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 1
  failureThreshold: 5
  successThreshold: 1
  timeoutSeconds: 1

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: overops.local
      paths: []
  tls: []
  #  - secretName: overops-tls
  #    hosts:
  #      - overops.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Persist data to a persistent volume
persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 20Gi
  annotations: {}

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
